+incdir+../../src/hvlTop/peripheralEnv/triggerMaster/
+incdir+../../src/hvlTop/peripheralEnv/triggerSlave/
+incdir+../../src/hvlTop/dmaControllerEnv/dmaControllerMasterAgent/
+incdir+../../src/hvlTop/dmaControllerEnv/dmaControllerSlaveAgent/
+incdir+../../src/hvlTop/dmaControllerEnv/dmaControllerVirtualSequencer
+incdir+../../src/hvlTop/peripheralEnv/peripheralVirtualSequencer
+incdir+../../src/hvlTop/configUnitEnv/configUnitVirtualSequencer/
+incdir+../../src/hvlTop/peripheralEnv/peripheralVirtualSequences/
+incdir+../../src/hvlTop/configUnitEnv/configUnitVirtualSequences/
+incdir+../../src/hvlTop/topEnv/topVirtualSequences/
+incdir+../../src/hvlTop/topEnv/topVirtualSequencer/
+incdir+../../src/hvlTop/configUnitEnv/interrupt/
+incdir+../../src/hvlTop/dmaTest/sequences/triggerSequences/
+incdir+../../src/hvlTop/dmaTest/sequences/axi4SlaveSequences/
+incdir+../../src/hvlTop/topEnv/subScoreboard/
../../src/globals/apbGlobalPkg.sv
../../src/globals/axiGlobalPkg.sv
../../src/globals/dmaGlobalPkg.sv
../../src/globals/triggerGlobalPkg.sv
../../src/globals/interruptGlobalPkg.sv
../../src/globals/bootGlobalPkg.sv

../../src/hvlTop/configUnitEnv/apbMaster/apbMasterPkg.sv
../../src/hvlTop/configUnitEnv/bootMaster/bootMasterPkg.sv
../../src/hvlTop/peripheralEnv/triggerMaster/triggerMasterPkg.sv
../../src/hvlTop/peripheralEnv/triggerSlave/triggerSlavePkg.sv 
../../src/hvlTop/dmaTest/sequences/triggerMasterSequences/triggerMasterSequencePkg.sv
../../src/hvlTop/configUnitEnv/interrupt/interruptSlavePkg.sv
../../src/hvlTop/configUnitEnv/configUnitEnvPkg.sv
../../src/hvlTop/configUnitEnv/configUnitVirtualSequences/configUnitVirtualSeqPkg.sv
../../src/hvlTop/peripheralEnv/axiMaster/axi4_master_pkg.sv
../../src/hvlTop/peripheralEnv/axiSlave/axi4_slave_pkg.sv
../../src/hvlTop/peripheralEnv/peripheralEnvPkg.sv
../../src/hvlTop/dmaTest/sequences/axi4SlaveSequences/axi4_slave_seq_pkg.sv
../../src/hvlTop/peripheralEnv/peripheralVirtualSequences/peripheralVirtualSeqPkg.sv
../../src/hvlTop/topEnv/topEnvPkg.sv
../../src/hvlTop/topEnv/topVirtualSequences/topVirtualSeqPkg.sv
../../src/hvlTop/dmaTest/dmaTestPkg.sv
../../src/hdlTop/axiInterface/axi4_if.sv
../../src/hdlTop/axiMasterAgentBfm/axi4_master_agent_bfm.sv
../../src/hdlTop/axiMasterAgentBfm/axi4_master_driver_bfm.sv
../../src/hdlTop/axiMasterAgentBfm/axi4_master_monitor_bfm.sv
../../src/hdlTop/axiSlaveAgentBfM/axi4_slave_monitor_bfm.sv
../../src/hdlTop/axiSlaveAgentBfM/axi4_slave_agent_bfm.sv
../../src/hdlTop/axiSlaveAgentBfM/axi4_slave_driver_bfm.sv
../../src/hdlTop/triggerMasterAgentBfm/triggerMasterAgentBfm.sv
../../src/hdlTop/triggerSlaveAgentBfm/triggerSlaveAgentBfm.sv
../../src/hdlTop/triggerInterface/triggerInterface.sv
../../src/hdlTop/triggerMasterAgentBfm/triggerMasterDriverBfm.sv
../../src/hdlTop/triggerMasterAgentBfm/triggerMasterMonitorBfm.sv
../../src/hdlTop/triggerSlaveAgentBfm/triggerSlaveDriverBfm.sv
../../src/hdlTop/triggerSlaveAgentBfm/triggerSlaveMonitorBfm.sv
../../src/hdlTop/apbInterface/apb_if.sv
../../src/hdlTop/apbMasterAgentBfm/apb_master_driver_bfm.sv
../../src/hdlTop/apbMasterAgentBfm/apb_master_monitor_bfm.sv
../../src/hdlTop/apbMasterAgentBfm/apb_master_agent_bfm.sv
../../src/hdlTop/interruptInterface/interruptInterface.sv
../../src/hdlTop/interruptSlaveAgentBfm/interruptSlaveDriverBfm.sv
../../src/hdlTop/interruptSlaveAgentBfm/interruptSlaveMonitorBfm.sv
../../src/hdlTop/interruptMasterAgentBfm/interruptMasterDriverBfm.sv
../../src/hdlTop/interruptMasterAgentBfm/interruptMasterMonitorBfm.sv
../../src/hdlTop/interruptSlaveAgentBfm/interruptSlaveAgentBfm.sv
../../src/hdlTop/interruptMasterAgentBfm/interruptMasterAgentBfm.sv
../../src/hvlTop/hvlTop.sv
../../src/hdlTop/bootInterface/bootInterface.sv  
../../src/hdlTop/bootMaster/bootMasterAgentBfm.sv 
../../src/hdlTop/bootMaster/bootMasterDriverBfm.sv 
../../src/hdlTop/bootMaster/bootMasterMonitorBfm.sv 
../../src/hdlTop/hdlTop.sv
../../src/hdlTop/interrconnect.sv
../../../RTL/apb_reg.v
../../../RTL/apb_slave.v
../../../RTL/cmd_fsm.v
../../../RTL/data_fsm.v
../../../RTL/dma_channel.v
../../../RTL/internal_reg.v
../../../RTL/mux.v
../../../RTL/mux_logic.v
../../../RTL/partselect.v
../../../RTL/register_bank.v
../../../RTL/top_mod.v
../../../RTL/trigger_matrix.v
../../../RTL/biu.v
../../../RTL/global_channel.v

